configure, refactored selection of GPU architectures
- moved from src/cudamatrix/Makefile to src/configure
- also fixes bug from xie7132524@gmail.com

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -427,6 +427,16 @@ function configure_cuda {
     echo CUDA = true >> kaldi.mk
     echo CUDATKDIR = $CUDATKDIR >> kaldi.mk
 
+    # Determine 'CUDA_ARCH',
+    CUDA_VERSION=$($CUDATKDIR/bin/nvcc -V | tr '.,' '_ ' | awk '/release/{sub(/.*release/,""); print $1;}') # MAJOR_MINOR,
+    case $CUDA_VERSION in
+      6_*) CUDA_ARCH="-gencode arch=compute_13,code=sm_13 -gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50" ;;
+      7_*) CUDA_ARCH="-gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_53,code=sm_53" ;;
+      *) echo "Missing CUDA_VERSION $CUDA_VERSION, see 'nvcc -h' which lists allowed -gencode values..."; exit 1 ;;
+    esac
+    echo "CUDA_ARCH = $CUDA_ARCH" >> kaldi.mk
+
+    # 64bit/32bit?
     if [ "`uname -m`" == "x86_64" ]; then
       if [ "`uname`" == "Darwin" ]; then
         sed 's/lib64/lib/g' < makefiles/cuda_64bit.mk >> kaldi.mk
@@ -436,6 +446,7 @@ function configure_cuda {
     else
       cat makefiles/cuda_32bit.mk >> kaldi.mk
     fi
+
   else
     echo "CUDA will not be used! If you have already installed cuda drivers "
     echo "and cuda toolkit, try using --cudatk-dir=... option.  Note: this is"
