trunk: script changes (compressed features are now default); improve configure script to add rpath to executable for Debian 7, so ld_library_path does not have to be messed with; some minor updates/extensions to nnet related programs; some minor script fixes.
git-svn-id: https://svn.code.sf.net/p/kaldi/code/trunk@3339 5e6a8d80-dfce-4ca6-a32a-6e07a63d50c8

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -375,8 +375,11 @@ function linux_configure_debian7 {
   for f in $ATLASLIBS; do 
     [ ! -f $f ] && return 1;
   done
+  libdir=$(dirname $(echo $ATLASLIBS | awk '{print $1}'))
+  [ -z "$libdir" ] && echo "Error getting libdir in linux_configure_debian7" && exit 1;
   echo ATLASINC = $ATLASROOT/include >> kaldi.mk
-  echo ATLASLIBS = $ATLASLIBS >> kaldi.mk
+  echo ATLASLIBS = $ATLASLIBS -Wl,-rpath=$libdir >> kaldi.mk
+  echo 
   cat makefiles/linux_atlas.mk >> kaldi.mk
   fix_cxx_flag
   echo "Successfully configured for Debian 7 [dynamic libraries] with ATLASLIBS =$ATLASLIBS"
