Fix to configure script RE openfst-1.2.10
git-svn-id: https://svn.code.sf.net/p/kaldi/code/trunk@717 5e6a8d80-dfce-4ca6-a32a-6e07a63d50c8

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -197,9 +197,11 @@ if [ ! -f $FSTROOT/include/fst/fst.h  ]; then
     failure "Could not find file $FSTROOT/include/fst/fst.h:
     you may not have installed OpenFst.  See ../tools/INSTALL"
 fi
-if ! cmp ../tools/minimize.h $FSTROOT/include/fst/minimize.h ; then
-    echo "**Warning: ../tools/minimize.h and $FSTROOT/include/fst/minimize.h differ: 
-    patch not applied?  FST tools may not work.  See ../tools/INSTALL"
+echo Checking OpenFst library was patched.
+if ! grep "multiple repeated" $FSTROOT/include/fst/minimize.h >/dev/null; then
+    echo "**Error: $FSTROOT/include/fst/minimize.h seems not to be patched:"
+    echo "patch not applied?  FST tools will not work in our recipe."
+    exit 1;
 fi
 
 # back up the old one in case we modified it
